title         : "Ledger"
url           : "http://marrus.xyz"
author        : "Gô SHOEMAKE"
blog_url      : "/ledger"
description   : "Gô's blog'"
lang          : "en"
permalink     : "/ledger/:categories/:title-0:year:month:day.html"
paginate      : 7
paginate_path : "/ledger/:num/"
timezone      : "US/Pacific"
markdown      : "kramdown"
kramdown:
    smart_quotes: ["apos", "apos", "quot", "quot"]
gems:
  - jekyll-redirect-from
  - jekyll-feed
defaults:
  -
    scope:
      path: ""
    values:
      author: "Gô SHOEMAKE"
feed:
  path: "/ledger/feed.xml"
